### ISSUE TITLE
what is this dollar sign?

### ISSUE THREAD

**Issue by cjunekim** [Aeldrion/AESTD#6]
This isn't an issue but rather a question. I didn't know where to post it so I put it here.

I looked into the functions and they looked great. But one thing that I couldn't figure out was $-1, $3, $1 and so on.

What are they? This is the first time I've seen it.

**Comment by nfitzen** [comment]
They're constants used for scoreboard operations.

Looking into it I just noticed that `aestd.core:scoreboard/v2_setup` doesn't initialize the constants properly. I'll make a PR for that.

**Comment by Aeldrion** [comment]
The dollar sign is often used as a convention to denote fake player names as players cannot have $ in their names. As nfitzen explained they're constants that I use in different functions (for example, for 2D Perlin noise, for random number generation, for time conversion...)
Also do note that this repository is not meant to be a final or stable version, I push untested changes every now and then and my workspace is often ahead of the latest commit. I've changed the scoreboard setup function a few times since then :p

**Comment by nfitzen** [comment]
@Aeldrion why don't you push the changes? I've been interested in contributing for a little bit, especially since I use the library in my own datapacks (luckily I haven't run into any issues for my uses yet). It's expected for a development branch to be somewhat unstable.
